### ISSUE TITLE
Plan to create a new release

### ISSUE THREAD

**Issue by jbdamiano** [travelping/gtplib#35]
Hello, 

it's not really an issue, 2 commits have been merged on your main branch, but no new release has been created on hex.pm

When do you plan to create a new release ?

Thanks

**Comment by vkatsuba** [comment]
Hi @jbdamiano the release with latest changes is created https://github.com/travelping/gtplib/releases/tag/3.1.0. Thanks for your contribution!

Best Regards,
--V
