### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by eshikafe** [travelping/gtplib#4]
I am unable to compile ppp on my Windows 7 PC.

C:\Users\eshikafe\Downloads\gtplib>rebar3 compile
===> Verifying dependencies...
===> Fetching erlando ({git,"https://github.com/travelping/erlando.git",
                            {ref,"8d1aa927c51b7ac351b90abcdaed7d2f527eb937"}})
===> Fetching lager ({pkg,<<"lager">>,<<"3.4.2">>})
===> Downloaded package, caching at c:/Users/eshikafe/.cache/rebar3/hex/default/packages/lager-3.4.2.tar
===> Fetching ppp ({git,"git://github.com/travelping/ppp",
                        {ref,"c1e03ee93ef333b5eb8aadd14b1290cfc1001089"}})
===> Failed to fetch and copy dep: {git,"git://github.com/travelping/ppp",
                                  {ref,
                                      "c1e03ee93ef333b5eb8aadd14b1290cfc1001089"}}

===> Verifying dependencies...
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Downloaded package, caching at c:/Users/eshikafe/.cache/rebar3/hex/default/packages/goldrush-0.1.9.tar
===> Fetching pmod_transform ({git,
                                  "git://github.com/erlang/pmod_transform.git",
                                  {ref,
                                      "7c6fe6193b7b11c874877246bcb612414fbd1359"}})
===> Failed to fetch and copy dep: {git,
                                  "git://github.com/erlang/pmod_transform.git",
                                  {ref,
                                      "7c6fe6193b7b11c874877246bcb612414fbd1359"}}

Are these deps really needed?

**Comment by RoadRunnr** [comment]
ppp is going to be the least of your problems when you try to run erGW (or anything that is supposed to speak GTP) on Windows.

Yes, the deps are needed and Windows is not supported by any of our Erlang projects. Linux is the only supported target, FreeBSD and Mac OSX might work, but are not tested.

If you absolutely have to use Windows, then the Windows Subsystem for Linux on Windows 10 might work. However, this also is not tested or will be supported by us.

**Comment by eshikafe** [comment]
Thanks. I want to test the gtplib as a standalone library on Windows.
I will just have to compile the modules I need for now on the Erlang shell.

**Comment by eshikafe** [comment]
It seems the issue was actually with connectivity to the deps repo:
I tried again on Windows and I was able to fetch all the deps

C:\Users\eshikafe\Downloads\gtplib>rebar3 compile
===> Verifying dependencies...
===> Fetching erlando ({git,"https://github.com/travelping/erlando.git",
                            {ref,"8d1aa927c51b7ac351b90abcdaed7d2f527eb937"}})
===> Fetching lager ({pkg,<<"lager">>,<<"3.4.2">>})
===> Downloaded package, caching at c:/Users/eshikafe/.cache/rebar3/hex/default/packages/lager-3.4.2.tar
===> Fetching ppp ({git,"git://github.com/travelping/ppp",
                        {ref,"c1e03ee93ef333b5eb8aadd14b1290cfc1001089"}})
===> Fetching eradius ({git,"https://github.com/travelping/eradius.git",
                            {ref,"19f06c3812482d479ec3982849a271291f439edb"}})
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Downloaded package, caching at c:/Users/eshikafe/.cache/rebar3/hex/default/packages/goldrush-0.1.9.tar
===> Fetching pmod_transform ({git,
                                  "git://github.com/erlang/pmod_transform.git",
                                  {ref,
                                      "7c6fe6193b7b11c874877246bcb612414fbd1359"}})
===> Fetching regine ({git,"https://github.com/travelping/regine.git",
                           {ref,"4c63d24ff798c785beb30d1447ace27611761dce"}})
===> Fetching coveralls ({git,"git://github.com/markusn/coveralls-erl.git",
                              {ref,"5f45f5a003244931acd5eabfa3db45a641188e2a"}})
===> Fetching exometer_core ({git,"git://github.com/Feuerlabs/exometer_core",
                                 {ref,
                                     "09c2a9361c0295c977e441ef89382db964a64460"}})
===> Fetching meck ({git,"git://github.com/eproxus/meck.git",
                         {ref,"ad8374ce5bdb0bb05d9f5a75d989157361902c3c"}})
===> Fetching folsom ({git,"git://github.com/folsom-project/folsom",
                           {ref,"38e2cce7c64ce1f0a3a918d90394cfc0a940b1ba"}})
===> Fetching hut ({git,"git://github.com/tolbrino/hut.git",
                        {ref,"025540398478ab6f95932c3234382ac5bb21ad3e"}})
===> Fetching parse_trans ({git,"git://github.com/uwiger/parse_trans.git",
                                {ref,"6f3645afb43c7c57d61b54ef59aecab288ce1013"}})
===> Fetching setup ({git,"git://github.com/uwiger/setup.git",
                          {ref,"e4a089f743505f1166e026c51989f041da7b2f6d"}})
===> Fetching bear ({git,"git://github.com/boundary/bear.git",
                         {ref,"119234548783af19b8ec75c879c5062676b92571"}})
===> Compiling meck
===> Compiling bear
_build/default/lib/bear/src/bear.erl:28: Warning: export_all flag enabled - all functions will be exported
_build/default/lib/bear/src/bear.erl:none: Warning: this system is not configured for native-code compilation.

**Comment by eshikafe** [comment]
I was able to compile gtplib on Windows 7 by modifying the following part of the eradius rebar config file:

Old:
{pre_hooks, [{compile, "./dicts_compiler.erl compile"},
             {clean, "./dicts_compiler.erl clean"}]}.

New (to work on Windows)
{pre_hooks, [{compile, "escript dicts_compiler.erl compile"},
             {clean, "escript dicts_compiler.erl clean"}]}.


C:\Users\eshikafe\Downloads\gtplib\_build\default\lib\gtplib\ebin>erl
Eshell V9.0  (abort with ^G)
1>
L = <<16#48,16#22,16#00,16#23,16#8a,16#81,16#f9,16#30,16#37,16#d6,16#a4,16#00,16#56,16#00,16#0d,16#00,16#18,16#26,16#f1,
16#03,16#2a,16#d6,16#26,16#f1,16#03,16#0d,16#bd,16#dc,16#06,16#52,16#00,16#01,16#00,16#06,16#03,16#00,16#01,16#00,16#0a>
>.
<<72,34,0,35,138,129,249,48,55,214,164,0,86,0,13,0,24,38,
  241,3,42,214,38,241,3,13,189,220,6,...>>
2> gtp_packet:decode(L).
{gtp,v2,modify_bearer_request,2323773744,3659428,undefined,
    [],
    #{{v2_rat_type,0} => {v2_rat_type,0,6},
      {v2_recovery,0} => {v2_recovery,0,10},
      {v2_user_location_information,0} =>
          {v2_user_location_information,0,undefined,undefined,
              undefined,
              <<38,241,3,42,214>>,
              <<38,241,3,13,189,220,6>>,
              undefined}}}
3>
