### ISSUE TITLE
Decapsulating GTPV2 header

### ISSUE THREAD

**Issue by imehrdad2012** [travelping/gtplib#5]
Hello,

I would like to remove GTPV2 header as well as its associated UDP/IP header from LTE packets sent by a LTE eNodeB. Would your library support this? Sorry if my question is basic.Thanks!

**Comment by RoadRunnr** [comment]
Sorry, I totally miss your question.

First, a eNode-B uses GTP-U v1 on the S1-U interface, there is no GTP-U v2.

The library supports decoding GTP-U v1, and GTP-C both v1 and v2. So, yes you can use it to strip the GTP-U header.

If you want to strip IP and/or UDP headers, you need to use a bit or Erlang binary matching to strip that.
